### PR TITLE
update(): Add messages and pics

### PR DESCRIPTION
**Pull request by Lordnoname**
Added new Tips of the day

### CODE REVIEW

**Comment by Lordnoname** [comment]
Please review `again` @IngolfSchmitt

**Comment by DevVersion** [comment]
LGTM

**Comment by Lordnoname** [comment]
I finally squashed my commits

**Comment by Eisphoenix** [comment]
LGTM

**Comment by DevVersion** [comment]
@IngolfSchmitt Maybe @Lordnoname can update his PR and remove the undesired lines and provide the sources of the images.

**Comment by DevVersion** [comment]
Is this ready for merge @Lordnoname?

**Pull request closed without merging**
